// Snapshot of note content for the daily email.
// Deno edge functions can't import from the Vite app's src/lib/note-data.ts,
// so the fields the daily email needs (title, body, receipt, caption,
// journal prompt) are mirrored here. Keep in sync with src/lib/note-data.ts
// if notes are added, removed, or edited.

export interface DailyNoteSnapshot {
  title: string;
  body: string;
  from: string;
  to: string;
  date: string;
  total: string;
  caption: string;
  journalPrompt: string;
}

export const notesSnapshot: DailyNoteSnapshot[] = [
  {
    title: "The Truth Was Too Heavy",
    body: `They asked,\n"How are you?"\nand this time,\nthey really meant it.\n\nThey looked at you\nlike they had space\nfor the truth.\n\nBut you still smiled.\nYou still said,\n"I'm fine."\n\nNot because\nthey did not care.\nNot because\nthey would not stay.\n\nBecause the truth\nwas too heavy\nto carry out loud.\n\nI hope you\nheal from\nthe fear\nof being honest\nwith people\nwho are safe enough\nto hear you.`,
    from: "Every time the truth climbed your throat and you swallowed it back down. every question you dodged with a smile. every night you cried alone because no one asked when you were ready to answer.",
    to: "One safe place. one person. one moment where you do not have to edit your pain.",
    date: "The first time someone asks and you do not flinch.",
    total: "The tears you saved for the dark. they are not shame. they are just waiting for permission.",
    caption: `They asked, "How are you?"\nand this time, they really meant it.\n\nBut you still smiled.\nYou still said, "I'm fine."\n\nBecause the truth\nwas too heavy\nto carry out loud.\n\nI hope you find one safe place\nwhere you do not have to edit your pain.`,
    journalPrompt: "What truth reached your throat but never became words?",
  },
  {
    title: "The Sentence That Stayed",
    body: `I hope you\nheal from\nthe words\nthat stayed\nlong after\nthe person\nwho said them\nmoved on.\n\nThe sentence\nthey forgot\nbecame something\nyou had to carry.\n\nBut what they said\nwas never your name.`,
    from: "Every sentence that entered your heart and started calling itself truth.",
    to: "The day your own voice becomes louder than what they said.",
    date: "The first time you remember it without becoming small again.",
    total: "The wound was real, but it was never your name.",
    caption: `I hope you heal from the words\nthat stayed long after\nthe person who said them moved on.\n\nThe sentence they forgot\nbecame something you had to carry.\n\nBut what they said\nwas never your name.`,
    journalPrompt: "What sentence are you still trying to stop believing?",
  },
  {
    title: "The Pain You Made Look Easy",
    body: `I hope you\nheal from\nall the pain\nyou made\nlook easy.\n\nFrom the days\nyou smiled\nbecause explaining\nwould have taken\ntoo much strength.\n\nFrom the nights\nyou broke quietly\nand still woke up\nlike nothing happened.`,
    from: "Every wound you dressed in strength so no one would worry.",
    to: "A life where surviving is not mistaken for being okay.",
    date: "The day you stop performing strength for people who never asked what it cost.",
    total: "You carried it well, but that does not mean it was light.",
    caption: `I hope you heal from all the pain\nyou made look easy.\n\nFrom the nights you broke quietly\nand still woke up like nothing happened.\n\nYou carried it well.\nThat does not mean it was light.`,
    journalPrompt: "Where have you been praised for strength when what you really needed was care?",
  },
  {
    title: "Distance Is My New Answer",
    body: `Distance is my new answer\nto disrespect.\n\nI no longer react.\nI no longer argue.\nI no longer dive\ninto drama.\n\nI simply remove\nmy presence.\n\nBecause some people\nthrow cruelty carelessly,\nthen call you sensitive\nfor bleeding.\n\nI hope you heal\nfrom the people\nwho made your reaction\nthe problem\ninstead of their actions.`,
    from: "Every argument that stole your peace.",
    to: "A silence that finally protects you.",
    date: "The day you stop explaining your absence.",
    total: "Your presence, returned to you.",
    caption: `Distance is my new answer\nto disrespect.\n\nI no longer react.\nI no longer argue.\nI simply remove my presence.\n\nBecause some people throw cruelty carelessly,\nthen call you sensitive for bleeding.`,
    journalPrompt: "Where do you need distance, not another explanation?",
  },
  {
    title: "The Unknown Number",
    body: `I hope you\nheal from\nthe unknown number\nthat makes\nyour stomach drop\nbefore you even answer.\n\nSome debts\nlive in the body,\nnot the bank.\n\nSome fear\narrives as a ringtone.`,
    from: "Every ring that felt like a judge.",
    to: "A phone that only brings news you can handle.",
    date: "The first month you do not flinch.",
    total: "Breathing through the whole day.",
    caption: `I hope you heal from the unknown number\nthat makes your stomach drop\nbefore you even answer.\n\nSome debts live in the body, not the bank.\nSome fear arrives as a ringtone.\n\nI hope your days become safe enough to breathe through.`,
    journalPrompt: "What does your body still react to before your mind can explain it?",
  },
  {
    title: "Grief in Your Thumb",
    body: `I hope you\nheal from\nstill reaching for\nthe phone number\nyou know\nwill not answer.\n\nFrom the habit\nof wanting to tell them\none more thing.\n\nFrom the silence\nthat arrives\nafter memory\ndials first.`,
    from: "Grief that lives in your thumb.",
    to: "A memory that no longer cuts.",
    date: "The first day love feels soft again.",
    total: "Missing them without losing yourself.",
    caption: `I hope you heal from still reaching for\nthe phone number you know will not answer.\n\nFrom the habit of wanting to tell them one more thing.\nFrom the silence that arrives after memory dials first.\n\nGrief has strange habits.\nI hope the memory becomes softer than the absence.`,
    journalPrompt: "What habit still carries someone you miss?",
  },
  {
    title: "When Shame Got There First",
    body: `I hope you\nheal from\nthe moments\nyou needed help\nbut chose silence\nbecause shame\ngot there first.\n\nFrom every time\nyour mouth opened,\nthen closed again\nbecause needing help\nfelt like failure.`,
    from: "Every prayer you whispered instead of asking someone.",
    to: "A hand that reaches before you collapse.",
    date: "The day help stops feeling like humiliation.",
    total: "You deserved support before survival became your only language.",
    caption: `I hope you heal from the moments you needed help\nbut chose silence because shame got there first.\n\nFrom every time your mouth opened,\nthen closed again,\nbecause needing help felt like failure.\n\nYou deserved support\nbefore survival became your only language.`,
    journalPrompt: "What help did you need before shame convinced you to stay silent?",
  },
  {
    title: "The Apology That Never Came",
    body: `I hope you\nheal from\nwaiting for\nthe apology\nthat never came.\n\nFrom checking\ntheir silence\nlike maybe\nremorse\nwas still on the way.\n\nSome people\nwill never name\nwhat they did.\n\nYou still deserve\nto be free.`,
    from: "Every wound that had to heal without a confession.",
    to: "A life that no longer waits for their honesty.",
    date: "The day closure stops needing their permission.",
    total: "Your peace, even without their apology.",
    caption: `I hope you heal from waiting for\nthe apology that never came.\n\nSome people will never name what they did.\n\nYou still deserve to be free.\n\nYour peace does not have to wait for their courage.`,
    journalPrompt: "What are you still waiting for them to admit?",
  },
  {
    title: "Remember Who You Are",
    body: `Always remind yourself\nof who you are.\n\nEspecially on the days\nlife makes you feel\nlike giving up.\n\nLook back.\n\nNot to stay there.\nBut to remember\nhow far you have walked\nwith wounds\nnobody saw.\n\nI hope you heal\nfrom the moments\nthat made you forget\nyour own strength.`,
    from: "Every version of you that survived what almost broke you.",
    to: "The person you are still becoming.",
    date: "The day you remember you did not come this far by accident.",
    total: "Your story is not over. You are still here.",
    caption: `Always remind yourself of who you are.\n\nEspecially on the days life makes you feel like giving up.\n\nLook back.\nNot to stay there.\nBut to remember how far you have walked\nwith wounds nobody saw.\n\nYou did not come this far by accident.`,
    journalPrompt: "What part of your story proves you are stronger than this moment?",
  },
  {
    title: "They Never Saw Your Road",
    body: `I hope you\nheal from\nthe people\nwho wish\nfor your fall\nwithout knowing\nthe graves\nyou walked past\nto get here.\n\nThey saw you standing.\nThey never saw\nwhat tried\nto bury you.`,
    from: "The nights you cried when no one was watching. the days you smiled through pain. the times you started over with nothing but hope.",
    to: "A single moment of peace without someone wishing you would fail.",
    date: 'The day someone says "I see your struggle" instead of "you do not belong."',
    total: "Every step you took when the ground was shaking beneath you. you cannot judge what you have not carried.",
    caption: `I hope you heal from the people\nwho wished for your fall\nwithout knowing the graves\nyou walked past to get here.\n\nThey saw you standing.\nThey never saw what tried to bury you.\n\nYou cannot judge what you have not carried.`,
    journalPrompt: "What part of your journey do people judge because they never had to carry it?",
  },
  {
    title: "Do It Anyway",
    body: `I hope you heal from\nthe people who knew your story\nbut still waited for strangers to clap\nbefore they supported you.\n\nThey knew what you survived.\n\nThey knew what you carried.\n\nThey knew the pit you crawled out of.\n\nAnd still, they waited.\n\nThey waited until money validated you.\n\nThey waited until the world\nstarted calling you successful.\n\nThey waited until it became safe\nto say they always believed in you.\n\nDo it anyway.\n\nStop expecting recognition\nfrom people who watched you bleed\nand still chose silence.\n\nBecome your own witness.\n\nYour own proof.\n\nYour own reason to keep going.\n\nBecause the dream was never given to the crowd.\n\nIt was given to you.`,
    from: "Every silent room where you expected support and received distance.",
    to: "The day you stop needing witnesses before you believe yourself.",
    date: "The moment you choose the dream without waiting for applause.",
    total: "Your proof was never their permission. Keep going.",
    caption: `Do it anyway.\n\nStop expecting recognition\nfrom people who watched you bleed\nand still chose silence.\n\nBecome your own witness.\nYour own proof.\nYour own reason to keep going.\n\nBecause the dream was never given to the crowd.\nIt was given to you.`,
    journalPrompt: "Where have you been waiting for recognition from people who already saw enough to support you?",
  },
  {
    title: "You Were Not Careless",
    body: `I hope you heal from the shame of counting money that was never enough.\n\nFrom checking your balance before buying bread.\n\nFrom knowing exactly how much is in your account because your peace has been living inside numbers.\n\nFrom pretending you are managing when you are really deciding which problem can wait until next week.\n\nPeople say money is not everything.\n\nBut they do not always understand that sometimes money is sleep.\n\nMoney is dignity.\n\nMoney is answering your phone without fear.\n\nMoney is not rehearsing an apology before someone asks for what you owe.\n\nMoney is walking into a shop without doing mathematics in your chest.\n\nYou have made small money perform miracles.\n\nYou have stretched what was already thin.\n\nYou have gone without and still looked normal.\n\nYou have smiled in rooms while calculating whether you can afford to get home.\n\nAnd the cruelest part is that people may still call it irresponsibility when they never saw how many times you chose survival over comfort.\n\nI hope you heal from blaming yourself for a life that kept asking you to carry more than the money could hold.\n\nI hope one day money stops feeling like proof of your worth.\n\nI hope one day your body no longer tightens when you hear the word "due."\n\nI hope one day you have enough to breathe.`,
    from: "Every month that asked you to become a miracle worker.",
    to: "The part of you that felt ashamed for not having enough.",
    date: "The first day you stop calling survival a failure.",
    total: "You were not careless. You were carrying more than the money could hold.",
    caption: `You have smiled in rooms while calculating whether you can afford to get home.\n\nYou have made small money perform miracles.\nYou have gone without and still looked normal.\n\nYou were not careless.\nYou were carrying more than the money could hold.`,
    journalPrompt: "Where have you been blaming yourself for financial pressure that was bigger than your choices?",
  },
  {
    title: "The Role Ended. You Did Not.",
    body: `I hope you heal from the morning after the job ended.\n\nThe morning when the alarm still knew your old life.\n\nThe morning your body woke up like it had somewhere to be, but your world had already changed.\n\nPeople may tell you to update your CV.\n\nTo network.\n\nTo stay positive.\n\nTo see it as redirection.\n\nAnd maybe one day you will.\n\nBut first, someone should say the truth.\n\nIt was not just a job.\n\nIt was your routine.\n\nYour answer when people asked what you do.\n\nYour proof that you were useful somewhere.\n\nYour way of paying bills without explaining yourself.\n\nYour place in the world, even if it was not perfect.\n\nSo when it ended, something in you lost its shape.\n\nNot your whole life.\n\nNot your value.\n\nBut something.\n\nAnd you are allowed to grieve that.\n\nYou are allowed to miss the emails, the access card, the desk, the salary, the small certainty of knowing where your mornings belonged.\n\nYou are allowed to feel embarrassed.\n\nYou are allowed to feel angry.\n\nYou are allowed to feel scared.\n\nLosing work can make a person feel like they have lost permission to stand tall.\n\nI hope you heal from tying your worth to a title that was never big enough to hold your whole life.\n\nI hope you find work again.\n\nBut before that, I hope you remember that your usefulness did not end when the role did.`,
    from: "The door that closed before you were ready.",
    to: "The version of you learning how to stand without the title.",
    date: "The morning you realize your usefulness did not end with the job.",
    total: "The role ended. You did not.",
    caption: `It was not just a job.\n\nIt was your routine.\nYour answer when people asked what you do.\nYour proof that you were useful somewhere.\n\nThe role ended.\nYou did not.`,
    journalPrompt: "What part of your identity did that job carry for you?",
  },
  {
    title: "It Ended, But It Was Not Nothing",
    body: `I hope you heal from the silence after a marriage changes shape.\n\nBecause people will ask what happened.\n\nThey will ask who was wrong.\n\nThey will ask whether there is still hope.\n\nThey will ask about papers, houses, children, family, and what comes next.\n\nBut very few people ask what it feels like to become a stranger to a life you once called home.\n\nMarriage is not only love.\n\nIt is shared towels.\n\nShared bills.\n\nShared beds.\n\nShared names in people's mouths.\n\nShared jokes no one else understands.\n\nShared plans that once sounded so certain.\n\nIt is someone knowing how you take your tea.\n\nIt is ordinary things becoming sacred because they belonged to two people.\n\nSo when it breaks, you do not only lose the person.\n\nYou lose the future you had already rehearsed.\n\nThe house you imagined.\n\nThe children you planned.\n\nThe old age you thought you would reach together.\n\nThe version of yourself that believed this would last.\n\nSo no, you are not dramatic for grieving something other people now discuss like paperwork.\n\nYou are grieving a covenant.\n\nA rhythm.\n\nA room.\n\nA name you thought would always sound like home.\n\nI hope you heal from the shame of loving something that could not stay whole.\n\nI hope you release without erasing.\n\nI hope you remember that a marriage becoming a memory does not mean your heart became a mistake.`,
    from: "The home that stopped feeling like home.",
    to: "The heart learning how to release without erasing.",
    date: "The day you stop calling your grief an embarrassment.",
    total: "It ended, but it was not nothing.",
    caption: `When it breaks, you do not only lose the person.\n\nYou lose the future you had already rehearsed.\nThe house you imagined.\nThe old age you thought you would reach together.\n\nIt ended, but it was not nothing.`,
    journalPrompt: "What future did you have to grieve quietly when the relationship changed?",
  },
  {
    title: "Missing Them Is Not the Same as Needing Them Back",
    body: `I hope you heal from the love that left before your heart knew how to let go.\n\nBecause some people do not only leave your life.\n\nThey leave your mornings different.\n\nYour phone quieter.\n\nYour plans unfinished.\n\nYour chest waiting for a message that is not coming.\n\nYour body checking places where they used to be.\n\nAnd the hardest part is not always that they left.\n\nSometimes the hardest part is that love stayed longer than they did.\n\nYou still remember their voice.\n\nTheir smell.\n\nTheir face when they were soft with you.\n\nThe small things nobody else knows how to replace.\n\nAnd now people expect you to move on as if love is a switch.\n\nAs if attachment obeys instructions.\n\nAs if the heart can forget just because the relationship ended.\n\nBut healing does not begin by pretending you no longer miss them.\n\nSometimes healing begins by admitting that you do.\n\nYou miss them.\n\nYou miss who you were with them.\n\nYou miss what you thought the two of you were becoming.\n\nThat does not mean you should go back.\n\nIt means you are human.\n\nI hope you heal from confusing missing them with needing them back.\n\nI hope memory becomes softer.\n\nI hope one day their name no longer feels like a door reopening inside you.`,
    from: "The love that left but did not leave your body quickly.",
    to: "The part of you still checking for what is no longer coming.",
    date: "The first day memory stops feeling like a wound reopening.",
    total: "Missing them is not the same as needing them back.",
    caption: `Some people do not only leave your life.\n\nThey leave your mornings different.\nYour phone quieter.\nYour chest waiting for a message that is not coming.\n\nMissing them is not the same as needing them back.\nThat does not mean you should go back.\nIt means you are human.`,
    journalPrompt: "What do you still miss that you are afraid to admit?",
  },
  {
    title: "Honoring Family Should Not Require Abandoning Yourself",
    body: `I hope you heal from the pain people told you not to name because it came from family.\n\nBecause when family hurts you, the world often asks you to understand.\n\nTo forgive.\n\nTo be mature.\n\nTo remember they are still your blood.\n\nBut sometimes blood is where the wound began.\n\nSometimes home was the first place you learned to stay quiet.\n\nSometimes family was the first place you learned to apologize for having feelings.\n\nSometimes the people who should have made you feel safe were the first people who made you feel difficult to love.\n\nAnd you have spent years being fair to people who were not always gentle with you.\n\nYou explained their behavior.\n\nYou defended their limitations.\n\nYou carried their history.\n\nYou made excuses for the way they loved you badly.\n\nBut love does not stop being painful because it came from family.\n\nAnd pain does not become small because the person who caused it shares your blood.\n\nYou are allowed to name what happened.\n\nYou are allowed to need distance.\n\nYou are allowed to protect the version of yourself that nobody protected then.\n\nI hope you heal from calling self protection disrespect.\n\nI hope you stop abandoning yourself just to keep peace with people who never asked what their peace cost you.`,
    from: "The home that taught you to be quiet about your own pain.",
    to: "The child in you who still wonders why love felt unsafe.",
    date: "The day you stop calling self protection disrespect.",
    total: "Family can explain the wound, but it does not excuse it.",
    caption: `I hope you heal from the pain people told you not to name because it came from family.\n\nSometimes blood is where the wound began.\n\nYou are allowed to name what happened.\nYou are allowed to protect the version of yourself\nthat nobody protected then.`,
    journalPrompt: "What family pain have you minimized because you were told to understand?",
  },
  {
    title: "You Were Not Hard to Love",
    body: `I hope you heal from the loneliness people cannot see because you still know how to function.\n\nBecause the hardest loneliness is not always an empty room.\n\nSometimes it is being surrounded by people who do not really know where you are inside yourself.\n\nPeople see you reply.\n\nThey see you laugh.\n\nThey see you show up.\n\nThey see you post.\n\nThey see you answer messages.\n\nThey see you keep moving.\n\nSo they assume you are fine.\n\nThey do not see the silence after the conversation ends.\n\nThey do not see how long you stare at your phone.\n\nThey do not see the part of you that wants someone to ask again, but differently.\n\nThey do not see how tired you are of being reachable but not really reached.\n\nYou are not lonely because nobody knows your name.\n\nYou are lonely because too few people know your weight.\n\nThe things you carry.\n\nThe things you avoid saying.\n\nThe truth behind your "I am okay."\n\nThe version of you that exists after everyone leaves.\n\nI hope you heal from having to collapse before people believe you needed someone.\n\nI hope one day you are known without performing pain.\n\nI hope someone sits beside your silence and does not rush to leave it.`,
    from: "Every room where you were present but still unseen.",
    to: "The part of you waiting to be known without performing pain.",
    date: "The first time someone stays long enough to notice the silence.",
    total: "You were not hard to love. You were hard to see from the surface.",
    caption: `I hope you heal from the loneliness people cannot see\nbecause you still know how to function.\n\nYou are not lonely because nobody knows your name.\nYou are lonely because too few people know your weight.\n\nYou were not hard to love.\nYou were hard to see from the surface.`,
    journalPrompt: "Where in your life do you feel surrounded but still unseen?",
  },
  {
    title: "Late Is Not Always Lost",
    body: `I hope you heal from the shame of still waiting for something you have worked so hard to become.\n\nBecause you are not always grieving failure.\n\nSometimes you are grieving delay.\n\nAnd delay has its own kind of heartbreak.\n\nYou can still believe in the dream and still be tired of waiting for it.\n\nYou can still know it is possible and still feel embarrassed that it has taken this long.\n\nYou can still be working hard and still feel like life is moving faster for everyone else.\n\nNobody tells you how heavy it is to carry a dream that keeps asking for more patience.\n\nMore faith.\n\nMore sacrifice.\n\nMore time.\n\nMore money.\n\nMore strength you are not sure you still have.\n\nAnd the hardest part is that people only celebrate dreams when they start looking successful.\n\nThey do not always see the years when the dream is still expensive.\n\nStill confusing.\n\nStill lonely.\n\nStill making you look foolish in rooms where results matter more than belief.\n\nBut delay is not always denial.\n\nSometimes delay is the place where the dream becomes honest.\n\nWhere you learn what part of it was ego.\n\nWhat part was calling.\n\nWhat part was pressure.\n\nWhat part was purpose.\n\nI hope you heal from measuring your calling only by speed.\n\nI hope you do not bury the dream just because it is late.\n\nBut I also hope you stop pretending the waiting has not hurt.`,
    from: "The years that made your dream look like it was not working.",
    to: "The part of you still believing without enough evidence.",
    date: "The day you stop measuring purpose only by speed.",
    total: "Late is not always lost.",
    caption: `You can still believe in the dream\nand still be tired of waiting for it.\n\nNobody tells you how heavy it is\nto carry a dream that keeps asking for more patience.\n\nBut delay is not always denial.\nLate is not always lost.`,
    journalPrompt: "What dream are you still carrying that feels late but not dead?",
  },
  {
    title: "Your Body Was Not Weak. It Was Honest.",
    body: `I hope you heal from calling your body weak when it was only trying to tell the truth.\n\nYour body has been speaking for a long time.\n\nBut you kept calling it laziness.\n\nMood.\n\nExcuses.\n\nA bad week.\n\nA lack of discipline.\n\nYou kept pushing because people needed you.\n\nBecause bills did not pause.\n\nBecause children still needed care.\n\nBecause work still expected performance.\n\nBecause life kept asking for output from a body that was already running on warning signs.\n\nSo your body started speaking louder.\n\nThrough headaches.\n\nThrough heaviness.\n\nThrough sleep that did not restore you.\n\nThrough tears that arrived without permission.\n\nThrough irritation.\n\nThrough numbness.\n\nThrough the kind of tired that rest alone could not fix.\n\nMaybe your body is not betraying you.\n\nMaybe it is telling the truth your mouth kept editing.\n\nYou have carried too much for too long without enough softness.\n\nYou do not need to earn rest by breaking down first.\n\nYou do not need to collapse before you are allowed to stop.\n\nI hope you heal from treating exhaustion like a personal failure.\n\nI hope you listen before your body has to scream.`,
    from: "The body that kept the score while you kept pretending.",
    to: "The part of you that thought exhaustion was a personal failure.",
    date: "The first time you listen before you collapse.",
    total: "Your body was not weak. It was honest.",
    caption: `You kept calling it laziness.\nMood. Excuses. A bad week.\n\nBut your body was not betraying you.\nIt was telling the truth your mouth kept editing.\n\nYour body was not weak. It was honest.\nYou do not need to earn rest by breaking down first.`,
    journalPrompt: "What has your body been trying to tell you that you keep explaining away?",
  },
  {
    title: "You Do Not Have to Do This Alone",
    body: `I hope you stay close to help tonight.\n\nNot because you have to explain everything.\n\nNot because you have to be strong.\n\nNot because you have to turn this pain into a lesson before morning.\n\nJust because this moment is too heavy to carry alone.\n\nIf staying feels hard today, let this be one small place where you do not have to pretend.\n\nYou do not have to solve your whole life right now.\n\nYou do not have to become hopeful immediately.\n\nYou do not have to make the pain sound smaller than it is.\n\nYou do not have to apologize for needing someone.\n\nJust stay with the next breath.\n\nThen the next one.\n\nThen the next.\n\nThere are days when life becomes too loud inside the body.\n\nDays when everything feels like too much.\n\nDays when even being told to be strong feels unfair.\n\nSo I will not ask you to be strong right now.\n\nI will ask you to move closer to safety.\n\nText someone.\n\nCall someone.\n\nSit where another human can see you.\n\nMove away from anything you could use to hurt yourself.\n\nGo to the safest room you can reach.\n\nLet one safe person know you are not okay.\n\nYou are not a burden because you need support.\n\nYou are not dramatic because this is heavy.\n\nYou are not weak because today is hard to carry.\n\nI hope you stay.\n\nNot because everything is fixed.\n\nBut because this moment is not the whole story.`,
    from: "The hour that felt too heavy to survive alone.",
    to: "The part of you that needs support, not shame.",
    date: "The moment you choose one more breath and one safe person.",
    total: "You do not have to do this alone.",
    caption: `You do not have to solve your whole life right now.\n\nJust stay with the next breath.\nThen the next one.\nThen the next.\n\nYou are not a burden because you need support.\nYou do not have to do this alone.`,
    journalPrompt: "Who is one safe person or support place you can reach before the night gets heavier?",
  },
];
