/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Volume1RouteImport } from './routes/volume-1'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShelfRouteImport } from './routes/shelf'
import { Route as SharePreviewRouteImport } from './routes/share-preview'
import { Route as SafetySupportRouteImport } from './routes/safety-support'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as PostcardPreviewRouteImport } from './routes/postcard-preview'
import { Route as PayForwardRouteImport } from './routes/pay-forward'
import { Route as NoteFramePreviewRouteImport } from './routes/note-frame-preview'
import { Route as GiftRouteImport } from './routes/gift'
import { Route as FeelingsRouteImport } from './routes/feelings'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Volume1IndexRouteImport } from './routes/volume-1.index'
import { Route as WriteCategorySlugRouteImport } from './routes/write.$categorySlug'
import { Route as Volume1UnlockRouteImport } from './routes/volume-1.unlock'
import { Route as Volume1PreviewRouteImport } from './routes/volume-1.preview'
import { Route as NoteCategorySlugRouteImport } from './routes/note.$categorySlug'
import { Route as Volume1ReadChapterRouteImport } from './routes/volume-1.read.$chapter'

const Volume1Route = Volume1RouteImport.update({
  id: '/volume-1',
  path: '/volume-1',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfRoute = ShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePreviewRoute = SharePreviewRouteImport.update({
  id: '/share-preview',
  path: '/share-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetySupportRoute = SafetySupportRouteImport.update({
  id: '/safety-support',
  path: '/safety-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostcardPreviewRoute = PostcardPreviewRouteImport.update({
  id: '/postcard-preview',
  path: '/postcard-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PayForwardRoute = PayForwardRouteImport.update({
  id: '/pay-forward',
  path: '/pay-forward',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteFramePreviewRoute = NoteFramePreviewRouteImport.update({
  id: '/note-frame-preview',
  path: '/note-frame-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftRoute = GiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const FeelingsRoute = FeelingsRouteImport.update({
  id: '/feelings',
  path: '/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Volume1IndexRoute = Volume1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Volume1Route,
} as any)
const WriteCategorySlugRoute = WriteCategorySlugRouteImport.update({
  id: '/write/$categorySlug',
  path: '/write/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const Volume1UnlockRoute = Volume1UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => Volume1Route,
} as any)
const Volume1PreviewRoute = Volume1PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => Volume1Route,
} as any)
const NoteCategorySlugRoute = NoteCategorySlugRouteImport.update({
  id: '/note/$categorySlug',
  path: '/note/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const Volume1ReadChapterRoute = Volume1ReadChapterRouteImport.update({
  id: '/read/$chapter',
  path: '/read/$chapter',
  getParentRoute: () => Volume1Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/collections': typeof CollectionsRoute
  '/feelings': typeof FeelingsRoute
  '/gift': typeof GiftRoute
  '/note-frame-preview': typeof NoteFramePreviewRoute
  '/pay-forward': typeof PayForwardRoute
  '/postcard-preview': typeof PostcardPreviewRoute
  '/reflect': typeof ReflectRoute
  '/safety-support': typeof SafetySupportRoute
  '/share-preview': typeof SharePreviewRoute
  '/shelf': typeof ShelfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/volume-1': typeof Volume1RouteWithChildren
  '/note/$categorySlug': typeof NoteCategorySlugRoute
  '/volume-1/preview': typeof Volume1PreviewRoute
  '/volume-1/unlock': typeof Volume1UnlockRoute
  '/write/$categorySlug': typeof WriteCategorySlugRoute
  '/volume-1/': typeof Volume1IndexRoute
  '/volume-1/read/$chapter': typeof Volume1ReadChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/collections': typeof CollectionsRoute
  '/feelings': typeof FeelingsRoute
  '/gift': typeof GiftRoute
  '/note-frame-preview': typeof NoteFramePreviewRoute
  '/pay-forward': typeof PayForwardRoute
  '/postcard-preview': typeof PostcardPreviewRoute
  '/reflect': typeof ReflectRoute
  '/safety-support': typeof SafetySupportRoute
  '/share-preview': typeof SharePreviewRoute
  '/shelf': typeof ShelfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/note/$categorySlug': typeof NoteCategorySlugRoute
  '/volume-1/preview': typeof Volume1PreviewRoute
  '/volume-1/unlock': typeof Volume1UnlockRoute
  '/write/$categorySlug': typeof WriteCategorySlugRoute
  '/volume-1': typeof Volume1IndexRoute
  '/volume-1/read/$chapter': typeof Volume1ReadChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/collections': typeof CollectionsRoute
  '/feelings': typeof FeelingsRoute
  '/gift': typeof GiftRoute
  '/note-frame-preview': typeof NoteFramePreviewRoute
  '/pay-forward': typeof PayForwardRoute
  '/postcard-preview': typeof PostcardPreviewRoute
  '/reflect': typeof ReflectRoute
  '/safety-support': typeof SafetySupportRoute
  '/share-preview': typeof SharePreviewRoute
  '/shelf': typeof ShelfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/today': typeof TodayRoute
  '/volume-1': typeof Volume1RouteWithChildren
  '/note/$categorySlug': typeof NoteCategorySlugRoute
  '/volume-1/preview': typeof Volume1PreviewRoute
  '/volume-1/unlock': typeof Volume1UnlockRoute
  '/write/$categorySlug': typeof WriteCategorySlugRoute
  '/volume-1/': typeof Volume1IndexRoute
  '/volume-1/read/$chapter': typeof Volume1ReadChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/collections'
    | '/feelings'
    | '/gift'
    | '/note-frame-preview'
    | '/pay-forward'
    | '/postcard-preview'
    | '/reflect'
    | '/safety-support'
    | '/share-preview'
    | '/shelf'
    | '/sitemap.xml'
    | '/support'
    | '/today'
    | '/volume-1'
    | '/note/$categorySlug'
    | '/volume-1/preview'
    | '/volume-1/unlock'
    | '/write/$categorySlug'
    | '/volume-1/'
    | '/volume-1/read/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/collections'
    | '/feelings'
    | '/gift'
    | '/note-frame-preview'
    | '/pay-forward'
    | '/postcard-preview'
    | '/reflect'
    | '/safety-support'
    | '/share-preview'
    | '/shelf'
    | '/sitemap.xml'
    | '/support'
    | '/today'
    | '/note/$categorySlug'
    | '/volume-1/preview'
    | '/volume-1/unlock'
    | '/write/$categorySlug'
    | '/volume-1'
    | '/volume-1/read/$chapter'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/collections'
    | '/feelings'
    | '/gift'
    | '/note-frame-preview'
    | '/pay-forward'
    | '/postcard-preview'
    | '/reflect'
    | '/safety-support'
    | '/share-preview'
    | '/shelf'
    | '/sitemap.xml'
    | '/support'
    | '/today'
    | '/volume-1'
    | '/note/$categorySlug'
    | '/volume-1/preview'
    | '/volume-1/unlock'
    | '/write/$categorySlug'
    | '/volume-1/'
    | '/volume-1/read/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CollectionsRoute: typeof CollectionsRoute
  FeelingsRoute: typeof FeelingsRoute
  GiftRoute: typeof GiftRoute
  NoteFramePreviewRoute: typeof NoteFramePreviewRoute
  PayForwardRoute: typeof PayForwardRoute
  PostcardPreviewRoute: typeof PostcardPreviewRoute
  ReflectRoute: typeof ReflectRoute
  SafetySupportRoute: typeof SafetySupportRoute
  SharePreviewRoute: typeof SharePreviewRoute
  ShelfRoute: typeof ShelfRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TodayRoute: typeof TodayRoute
  Volume1Route: typeof Volume1RouteWithChildren
  NoteCategorySlugRoute: typeof NoteCategorySlugRoute
  WriteCategorySlugRoute: typeof WriteCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volume-1': {
      id: '/volume-1'
      path: '/volume-1'
      fullPath: '/volume-1'
      preLoaderRoute: typeof Volume1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf': {
      id: '/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof ShelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-preview': {
      id: '/share-preview'
      path: '/share-preview'
      fullPath: '/share-preview'
      preLoaderRoute: typeof SharePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-support': {
      id: '/safety-support'
      path: '/safety-support'
      fullPath: '/safety-support'
      preLoaderRoute: typeof SafetySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postcard-preview': {
      id: '/postcard-preview'
      path: '/postcard-preview'
      fullPath: '/postcard-preview'
      preLoaderRoute: typeof PostcardPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-forward': {
      id: '/pay-forward'
      path: '/pay-forward'
      fullPath: '/pay-forward'
      preLoaderRoute: typeof PayForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-frame-preview': {
      id: '/note-frame-preview'
      path: '/note-frame-preview'
      fullPath: '/note-frame-preview'
      preLoaderRoute: typeof NoteFramePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift': {
      id: '/gift'
      path: '/gift'
      fullPath: '/gift'
      preLoaderRoute: typeof GiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feelings': {
      id: '/feelings'
      path: '/feelings'
      fullPath: '/feelings'
      preLoaderRoute: typeof FeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume-1/': {
      id: '/volume-1/'
      path: '/'
      fullPath: '/volume-1/'
      preLoaderRoute: typeof Volume1IndexRouteImport
      parentRoute: typeof Volume1Route
    }
    '/write/$categorySlug': {
      id: '/write/$categorySlug'
      path: '/write/$categorySlug'
      fullPath: '/write/$categorySlug'
      preLoaderRoute: typeof WriteCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume-1/unlock': {
      id: '/volume-1/unlock'
      path: '/unlock'
      fullPath: '/volume-1/unlock'
      preLoaderRoute: typeof Volume1UnlockRouteImport
      parentRoute: typeof Volume1Route
    }
    '/volume-1/preview': {
      id: '/volume-1/preview'
      path: '/preview'
      fullPath: '/volume-1/preview'
      preLoaderRoute: typeof Volume1PreviewRouteImport
      parentRoute: typeof Volume1Route
    }
    '/note/$categorySlug': {
      id: '/note/$categorySlug'
      path: '/note/$categorySlug'
      fullPath: '/note/$categorySlug'
      preLoaderRoute: typeof NoteCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume-1/read/$chapter': {
      id: '/volume-1/read/$chapter'
      path: '/read/$chapter'
      fullPath: '/volume-1/read/$chapter'
      preLoaderRoute: typeof Volume1ReadChapterRouteImport
      parentRoute: typeof Volume1Route
    }
  }
}

interface Volume1RouteChildren {
  Volume1PreviewRoute: typeof Volume1PreviewRoute
  Volume1UnlockRoute: typeof Volume1UnlockRoute
  Volume1IndexRoute: typeof Volume1IndexRoute
  Volume1ReadChapterRoute: typeof Volume1ReadChapterRoute
}

const Volume1RouteChildren: Volume1RouteChildren = {
  Volume1PreviewRoute: Volume1PreviewRoute,
  Volume1UnlockRoute: Volume1UnlockRoute,
  Volume1IndexRoute: Volume1IndexRoute,
  Volume1ReadChapterRoute: Volume1ReadChapterRoute,
}

const Volume1RouteWithChildren =
  Volume1Route._addFileChildren(Volume1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CollectionsRoute: CollectionsRoute,
  FeelingsRoute: FeelingsRoute,
  GiftRoute: GiftRoute,
  NoteFramePreviewRoute: NoteFramePreviewRoute,
  PayForwardRoute: PayForwardRoute,
  PostcardPreviewRoute: PostcardPreviewRoute,
  ReflectRoute: ReflectRoute,
  SafetySupportRoute: SafetySupportRoute,
  SharePreviewRoute: SharePreviewRoute,
  ShelfRoute: ShelfRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TodayRoute: TodayRoute,
  Volume1Route: Volume1RouteWithChildren,
  NoteCategorySlugRoute: NoteCategorySlugRoute,
  WriteCategorySlugRoute: WriteCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
